/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.google.common.util.concurrent.Service;

import java.sql.SQLOutput;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        System.out.println("*** Welcome ASK Institute Of Coding ***");

        Scanner sc = new Scanner(System.in);

        System.out.println("Enter User ID : ");
        String  UserId = sc.nextLine();

        System.out.println("Enter Password : ");
        String Hashpass = sc.nextLine();

        User user = UserService.authtication(UserId , Hashpass);

        if(user != null){
            System.out.println("You are Logged Successfully");

            System.out.println(" ");
            System.out.println(" *** Your Profile ***");
            System.out.println("Name : " +user.FullName);
            System.out.println("User ID : " +user.UserId);
            System.out.println("Age : " + user.age);

        }
        else {
            System.out.println("Invalid UserId and Password");
        }
    }
}
